name: dartion
description: Dartion is a RESTful mini web server based on JSON. Up your backend in 5 Seconds!
version: 1.0.6
homepage: https://github.com/Flutterando/dartion

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  yaml: ^3.1.0
  jaguar_jwt: ^3.0.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_multipart: ^0.1.0
  uuid: ^3.0.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  dartion: dartion