name: dartion
description: Dartion is a RESTful mini web server based on JSON. Up your backend in 5 Seconds!
version: 0.0.6
homepage: https://github.com/Flutterando/dartion

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.7.0
  yaml: ^2.2.0
  jaguar_jwt: ^2.1.6
  http_server: ^0.9.8+3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  dartion: main