name: dartion
description: Json Server RESTful
version: 0.0.2
homepage: https://github.com/Flutterando/dartion

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: ^2.2.0
  jaguar_jwt: ^2.1.6

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  dartion: main
