name: dartion
description: Dartion is a RESTful mini web server based on JSON. Up your backend in 5 Seconds!
version: 1.2.0
homepage: https://github.com/Flutterando/dartion

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaguar_jwt: ^3.0.0
  path: ^1.8.3
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  uuid: ^3.0.7
  yaml: ^3.1.1

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.24.3

executables:
  dartion: dartion